//! Portable implementations of named Kirikiri plugins, installed by the host.
//! Engine classes remain owned by the engine; no foreign DLL ABI is loaded.
mod about;
mod alpha;
mod alpha_movie;
mod base64;
mod clipboard;
mod csv;
mod dialog;
mod dirlist;
mod draw_device;
mod drawing;
mod emote;
mod equations;
mod expat;
mod exports;
mod extrans;
mod fftgraph;
mod files;
mod filter;
mod font;
mod geometry;
mod gfx;
mod image;
mod json;
mod kag;
mod ksupport;
mod layer_draw;
mod layer_filter;
mod layer_save;
mod lzfs;
mod menu_focus;
mod minizip;
mod movie;
mod nagano;
mod particle;
mod perspective;
mod psb;
mod psd;
mod qrcode;
mod raster;
mod registory;
mod sample;
mod save_struct;
mod screen;
mod scripts_ex;
mod shrink;
#[cfg(feature = "sqlite")]
mod sqlite;
mod string_util;
mod table;
mod text_render;
mod timeline;
mod varfile;
mod wave;
mod win32ole;
mod window;
mod xp3filter;
mod ya_draw;
use krkr_engine::plugins;
use tjs_core::{Heap, NativeResult};
pub use xp3filter::{script_filter, script_filter_checked};

pub fn register(heap: &mut Heap) -> NativeResult<()> {
    about::About::register(heap)?;
    equations::Equations::register(heap)?;
    menu_focus::MenuFocus::register(heap)?;
    base64::Base64::register(heap)?;
    wave::Vorbis::register(heap)?;
    wave::Tcwf::register(heap)?;
    wave::Opus::register(heap)?;
    wave::Ffmpeg::register(heap)?;
    sample::Sample::register(heap)?;
    text_render::TextRender::register(heap)?;
    #[cfg(feature = "sqlite")]
    sqlite::Sqlite::register(heap)?;
    alpha::Alpha::register(heap)?;
    alpha_movie::AlphaMovie::register(heap)?;
    expat::Expat::register(heap)?;
    qrcode::Qrcode::register(heap)?;
    registory::Registory::register(heap)?;
    win32ole::Ole::register(heap)?;
    plugins::register_class_alias(heap, &["krmovie.dll", "krmovie.tpm"], "VideoOverlay")?;
    fftgraph::FftGraph::register(heap)?;
    filter::LegacyFilter::register(heap)?;
    gfx::Gfx::register(heap)?;
    kag::KagEx::register(heap)?;
    kag::ExtKag::register(heap)?;
    minizip::Minizip::register(heap)?;
    varfile::VarFile::register(heap)?;
    lzfs::Lzfs::register(heap)?;
    shrink::Shrink::register(heap)?;
    dirlist::DirList::register(heap)?;
    dialog::Dialog::register(heap)?;
    xp3filter::Xp3Filter::register(heap)?;
    font::AddFont::register(heap)?;
    extrans::Extrans::register(heap)?;
    nagano::Nagano::register(heap)?;
    image::Image::register(heap)?;
    raster::Raster::register(heap)?;
    raster::AreaAverage::register(heap)?;
    movie::Movie::register(heap)?;
    layer_save::Save::register(heap)?;
    layer_draw::LayerDraw::register(heap)?;
    psd::Psd::register(heap)?;
    psb::Psb::register(heap)?;
    emote::Emote::register(heap)?;
    draw_device::DrawDevice::register(heap)?;
    perspective::Perspective::register(heap)?;
    particle::Particles::register(heap)?;
    ya_draw::YaDraw::register(heap)?;
    layer_filter::LayerFilter::register(heap)?;
    scripts_ex::ScriptsEx::register(heap)?;
    string_util::StringUtil::register(heap)?;
    save_struct::SaveStruct::register(heap)?;
    csv::Csv::register(heap)?;
    window::Window::register(heap)?;
    screen::Screen::register(heap)?;
    plugins::register_class_alias(heap, &["menu.dll", "menu.tpm"], "MenuItem")?;
    plugins::register_class_alias(heap, &["KAGParser.dll", "KAGParser.tpm"], "KAGParser")?;
    ksupport::Support::register(heap)?;
    clipboard::Clipboard::register(heap)?;
    json::Json::register(heap)?;
    files::Files::register(heap)?;
    Ok(())
}
