/// Declare a provider whose lifetime consists of managed classes and methods.
/// Aliases share one provider; exports use Context's transaction and restore
/// previous slots on unlink. Resource-owning providers implement Plugin directly
/// and reuse Exports, keeping their lease/cleanup decisions explicit.
///
/// ```ignore
/// krkr_engine::native_plugin! {
///     pub(crate) Csv {
///         names: ["csvParser.dll", "csvParser.tpm"],
///         classes: [parser], // module generated by #[tjs_bind::class]
///         extensions: [],
///     }
/// }
/// ```
/// For captures, flags, properties or grouped installers use
/// `link(cx, exports) { ...; Ok(()) }` in place of classes/extensions. The hook
/// receives a fresh pending export set; a failed link drops it. An optional
/// `unlink(cx, exports) { ...; exports.unlink(cx) }` retains explicit cleanup
/// and may refuse unloading with Ok(false). Direct Heap mutations remain outside
/// the export transaction. See clipboard/saveStruct for captures, and PSD for
/// a resource-owning Plugin using `native_plugin! { impl Psd { names: [...] } }`.
#[macro_export]
macro_rules! native_plugin {
    (impl $name:ty { names: [$($alias:literal),+ $(,)?] $(,)? }) => {
        impl $name {
            pub fn register(heap: &mut $crate::plugins::__tjs::Heap) -> $crate::plugins::__tjs::NativeResult<()> {
                $crate::plugins::register(heap, &[$($alias),+], Self::default())
            }
        }
    };
    ($vis:vis $name:ident {
        names: [$($alias:literal),+ $(,)?],
        link($cx:ident, $exports:ident) $link:block
        $(unlink($unlink_cx:ident, $unlink_exports:ident) $unlink:block)?
    }) => {
        #[derive(Default)]
        $vis struct $name($crate::plugins::Exports);
        impl $crate::plugins::__tjs::Trace for $name {
            fn trace(&self, visit: &mut dyn FnMut($crate::plugins::__tjs::Value)) {
                $crate::plugins::__tjs::Trace::trace(&self.0, visit);
            }
        }
        impl $crate::plugins::Plugin for $name {
            fn link(&mut self, $cx: &mut $crate::plugins::Context<'_>) -> $crate::plugins::__tjs::NativeResult<()> {
                let mut pending = $crate::plugins::Exports::default();
                let $exports = &mut pending;
                let _ = (&$cx, &$exports);
                let result: $crate::plugins::__tjs::NativeResult<()> = (|| $link)();
                result?;
                self.0 = pending;
                Ok(())
            }
            fn unlink(&mut self, cx: &mut $crate::plugins::Context<'_>) -> $crate::plugins::__tjs::NativeResult<bool> {
                $crate::native_plugin!(@unlink self, cx; $( $unlink_cx, $unlink_exports, $unlink )?)
            }
        }
        impl $name {
            pub fn register(heap: &mut $crate::plugins::__tjs::Heap) -> $crate::plugins::__tjs::NativeResult<()> {
                $crate::plugins::register(heap, &[$($alias),+], Self::default())
            }
        }
    };
    (@unlink $provider:ident, $cx:ident;) => { $provider.0.unlink($cx) };
    (@unlink $provider:ident, $cx:ident; $context:ident, $exports:ident, $body:block) => {{
        let $context = $cx;
        let $exports = &mut $provider.0;
        $body
    }};
    ($vis:vis $name:ident {
        names: [$($alias:literal),+ $(,)?],
        classes: [$($binding:path),* $(,)?],
        extensions: [$(($owner:literal, $member:literal, $call:expr)),* $(,)?] $(,)?
    }) => {
        $crate::native_plugin! {
            $vis $name {
                names: [$($alias),+],
                link(cx, exports) {
                $( {
                    use $binding as binding;
                    let class = binding::install(cx.heap)?;
                    exports.value(cx, cx.global, binding::CLASS.name, $crate::plugins::__tjs::Value::Obj(class.into()))?;
                } )*
                $( {
                    let owner = cx.heap.registered_class($owner).ok_or(
                        $crate::plugins::__tjs::NativeError::Message("required engine class is not installed")
                    )?;
                    exports.function(cx, owner, $member, $call)?;
                } )*
                Ok(())
                }
            }
        }
    };
}

struct EngineClass(&'static str);
impl tjs_core::Trace for EngineClass {
    fn trace(&self, _: &mut dyn FnMut(tjs_core::Value)) {}
}
impl super::Plugin for EngineClass {
    fn link(&mut self, cx: &mut super::Context<'_>) -> tjs_core::NativeResult<()> {
        let class = cx
            .heap
            .registered_class(self.0)
            .ok_or(tjs_core::NativeError::Message(
                "plugin requires its engine class",
            ))?;
        cx.export(self.0, tjs_core::Value::Obj(class.into()))
    }
    fn unlink(&mut self, _: &mut super::Context<'_>) -> tjs_core::NativeResult<bool> {
        // Alias names release independently of preinstalled classes/instances.
        Ok(true)
    }
}
/// Register legacy plugin names for a class already owned by the engine.
/// Releasing the last name preserves the class's normal engine lifetime.
pub fn register_class_alias(
    heap: &mut tjs_core::Heap,
    names: &[&str],
    class: &'static str,
) -> tjs_core::NativeResult<()> {
    super::register(heap, names, EngineClass(class))
}
