[package]
name = "krkr-protocol"
version.workspace = true
edition = "2024"
rust-version = "1.95"

[features]
profiling = ["dep:serde", "dep:serde_json"]

[dependencies]
thiserror.workspace = true
slotmap.workspace = true
lru = "0.16"
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }

[lints]
workspace = true
